/* НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ - он генерируется автоматически */
/*     DO NOT EDIT THIS FILE - it is machine generated       */
#include <jni.h>
/* Заголовок для класса ru.aot.morph.JavaMorphAPI */

#ifndef _Included_ru_aot_morph_JavaMorphAPI
#define _Included_ru_aot_morph_JavaMorphAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Класс:     ru_aot_morph_JavaMorphAPI
 * Метод:     lookupWordImpl
 * Сигнатура: (I[B)Lru/aot/morph/JavaMorphAPI/РезультатСлова;
 */
JNIEXPORT jobject JNICALL Java_ru_aot_morph_JavaMorphAPI_lookupWordImpl
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Класс:     ru_aot_morph_JavaMorphAPI
 * Метод:     lookupFormImpl
 * Сигнатура: (I[B)Lru/aot/morph/JavaMorphAPI/РезультатСлова;
 */
JNIEXPORT jobject JNICALL Java_ru_aot_morph_JavaMorphAPI_lookupFormImpl
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Класс:     ru_aot_morph_JavaMorphAPI
 * Метод:     initImpl
 * Сигнатура: (ILjava/lang/Строка;)V
 */
JNIEXPORT void JNICALL Java_ru_aot_morph_JavaMorphAPI_initImpl
  (JNIEnv *, jclass, jint, jstring);

/*
 * Класс:     ru_aot_morph_JavaMorphAPI
 * Метод:     closeImpl
 * Сигнатура: ()V
 */
JNIEXPORT void JNICALL Java_ru_aot_morph_JavaMorphAPI_closeImpl
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
