/* НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ - он генерируется автоматически */
/*     DO NOT EDIT THIS FILE - it is machine generated       */
#include <jni.h>
/* Заголовок для класса ru.aot.morph.JavaMorphAPI.Граммема */

#ifndef _Included_ru_aot_morph_JavaMorphAPI_\u0413\u0440\u0430\u043c\u043c\u0435\u043c\u0430
#define _Included_ru_aot_morph_JavaMorphAPI_\u0413\u0440\u0430\u043c\u043c\u0435\u043c\u0430
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
