/* НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ - он генерируется автоматически */
/*     DO NOT EDIT THIS FILE - it is machine generated       */
#include <jni.h>
/* Заголовок для класса ru.aot.morph.JavaMorphAPI.ЧастьРечи */

#ifndef _Included_ru_aot_morph_JavaMorphAPI_\u0427\u0430\u0441\u0442\u044c\u0420\u0435\u0447\u0438
#define _Included_ru_aot_morph_JavaMorphAPI_\u0427\u0430\u0441\u0442\u044c\u0420\u0435\u0447\u0438
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
