/* НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ - он генерируется автоматически */
/*     DO NOT EDIT THIS FILE - it is machine generated       */
#include <jni.h>
/* Заголовок для класса ru.aot.morph.JavaMorphAPI.РезультатСлова */

#ifndef _Included_ru_aot_morph_JavaMorphAPI_\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u0421\u043b\u043e\u0432\u0430
#define _Included_ru_aot_morph_JavaMorphAPI_\u0420\u0435\u0437\u0443\u043b\u044c\u0442\u0430\u0442\u0421\u043b\u043e\u0432\u0430
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
