/* НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ - он генерируется автоматически */
/*     DO NOT EDIT THIS FILE - it is machine generated       */
#include <jni.h>
/* Заголовок для класса ru_aot_morph_JavaMorphAPI_\u042f\u0437\u044b\u043a */

#ifndef _Included_ru_aot_morph_JavaMorphAPI_\u042f\u0437\u044b\u043a
#define _Included_ru_aot_morph_JavaMorphAPI_\u042f\u0437\u044b\u043a
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
