/* НЕ РЕДАКТИРУЙТЕ ЭТОТ ФАЙЛ - он генерируется автоматически */
/*     DO NOT EDIT THIS FILE - it is machine generated       */
#include <jni.h>
/* Заголовок для класса ru_aot_morph_JavaMorphAPI */

#ifndef _Included_ru_aot_morph_JavaMorphAPI
#define _Included_ru_aot_morph_JavaMorphAPI
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Класс:     ru_aot_morph_JavaMorphAPI
 * Метод:    реализНайдиСлово
 * Сигнатура: (I[B)Lru/aot/morph/JavaMorphAPI/РезультатСлова;
 */
JNIEXPORT jobject JNICALL Java_ru_aot_morph_JavaMorphAPI_\u0440\u0435\u0430\u043b\u0438\u0437\u041d\u0430\u0439\u0434\u0438\u0421\u043b\u043e\u0432\u043e
  (JNIEnv *, jclass, jint, jbyteArray);

/*
 * Класс:     ru_aot_morph_JavaMorphAPI
 * Метод:    реализОбозначив
 * Сигнатура: (I)V
 */
JNIEXPORT void JNICALL Java_ru_aot_morph_JavaMorphAPI_\u0440\u0435\u0430\u043b\u0438\u0437\u041e\u0431\u043e\u0437\u043d\u0430\u0447\u0438\u0432
  (JNIEnv *, jclass, jint);

/*
 * Класс:     ru_aot_morph_JavaMorphAPI
 * Метод:    реализЗакрой
 * Сигнатура: ()V
 */
JNIEXPORT void JNICALL Java_ru_aot_morph_JavaMorphAPI_\u0440\u0435\u0430\u043b\u0438\u0437\u0417\u0430\u043a\u0440\u043e\u0439
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
