include ../common/common_mak
ExeName = GraphmatThick$(ExeExten)
objects = GraphmatThick.o$(ct) 

libs = \
../GraphanLib/libGraphan$(ct).$(lib_ext) \
../StructDictLib/libStructDict$(ct).$(lib_ext)

cparams += -fPIC

include ../common/common_exe_mak
