objects +=  \
../AgramtabLib/agramtab_.o$(ct)\
../AgramtabLib/EngGramTab.o$(ct)\
../AgramtabLib/GerGramTab.o$(ct)\
../AgramtabLib/RusGramTab.o$(ct)\
../AgramtabLib/StdGramtab.o$(ct)\
../BinaryDictsLib/AspPairDict.o$(ct)\
../BinaryDictsLib/BinaryDictionary.o$(ct)\
../BinaryDictsLib/DerivDict.o$(ct)\
../BinaryDictsLib/FreqDict.o$(ct)\
../BinaryDictsLib/SetOfWordPairs.o$(ct)\
../BinaryDictsLib/SynDictionary.o$(ct)\
../CheckGramTab/CheckGramTab.o$(ct)\
../common/AncodePattern.o$(ct)\
../common/BigramsReader.o$(ct)\
../common/gra_descr.o$(ct)\
../common/Homonym.o$(ct)\
../common/iconv_cpp.o$(ct)\
../common/LemWord.o$(ct)\
../common/MorphologyHolder.o$(ct)\
../common/MorphXmlToken.o$(ct)\
../common/PlmLine.o$(ct)\
../common/RusCorpXml.o$(ct)\
../common/rus_numerals.o$(ct)\
../common/string_socket.o$(ct)\
../common/SyntaxHolder.o$(ct)\
../common/utilit.o$(ct)\
../EngSynanLib/EngFormatCaller.o$(ct)\
../EngSynanLib/EngOborDic.o$(ct)\
../EngSynanLib/EngSentence.o$(ct)\
../EngSynanLib/EngSyntaxOpt.o$(ct)\
../GerPostMorph/GermanPostMorph.o$(ct)\
../GraphanLib/abbrev.o$(ct)\
../GraphanLib/C_desc.o$(ct)\
../GraphanLib/Consent.o$(ct)\
../GraphanLib/Cs_hiera.o$(ct)\
../GraphanLib/graline.o$(ct)\
../GraphanLib/GraphanDicts.o$(ct)\
../GraphanLib/GraphmatFile.o$(ct)\
../GraphanLib/HtmlConv.o$(ct)\
../GraphanLib/Nc_desc.o$(ct)\
../GraphanLib/Oborots.o$(ct)\
../GraphanLib/Sentences.o$(ct)\
../GraphanLib/UnitHolder.o$(ct)\
../GraphanLib/Writegra.o$(ct)\
../LemmatizerLib/CreatePredictionBase.o$(ct)\
../LemmatizerLib/Lemmatizers.o$(ct)\
../LemmatizerLib/MorphAutomat.o$(ct)\
../LemmatizerLib/MorphAutomBuilder.o$(ct)\
../LemmatizerLib/MorphDictBuilder.o$(ct)\
../LemmatizerLib/MorphDict.o$(ct)\
../LemmatizerLib/Paradigm.o$(ct)\
../LemmatizerLib/PLMLineCollection.o$(ct)\
../LemmatizerLib/Predict.o$(ct)\
../LemmatizerLib/Statistic.o$(ct)\
../LemmatizerLib/StdMorph.o$(ct)\
../MAPostLib/Fio.o$(ct)\
../MAPostLib/MAPostInit.o$(ct)\
../MAPostLib/MAPostMain.o$(ct)\
../MAPostLib/PostLemWord.o$(ct)\
../MorphWizardLib/wizard.o$(ct)\
../RmlThesLib/Concepts.o$(ct)\
../RmlThesLib/Models.o$(ct)\
../RmlThesLib/Relats.o$(ct)\
../RmlThesLib/StdRmlThes.o$(ct)\
../RmlThesLib/Synonyms.o$(ct)\
../RmlThesLib/Termins.o$(ct)\
../RmlThesLib/Thesaurus.o$(ct)\
../RmlThesLib/ThesOborots.o$(ct)\
../SimpleGrammarLib/AhoKorasick.o$(ct)\
../SimpleGrammarLib/ChunkNode.o$(ct)\
../SimpleGrammarLib/ChunkParser.o$(ct)\
../SimpleGrammarLib/FirstAndFollow.o$(ct)\
../SimpleGrammarLib/GetMaxCoverage.o$(ct)\
../SimpleGrammarLib/GLR.o$(ct)\
../SimpleGrammarLib/GLRTable.o$(ct)\
../SimpleGrammarLib/GrammarItem.o$(ct)\
../SimpleGrammarLib/Loader.o$(ct)\
../SimpleGrammarLib/LR-items.o$(ct)\
../SimpleGrammarLib/Parser.o$(ct)\
../SimpleGrammarLib/SimpleGrammarLib.o$(ct)\
../SimpleGrammarLib/SolvePeriodAmbiguity.o$(ct)\
../SimpleGrammarLib/SourceGrammarParser.o$(ct)\
../SimpleGrammarLib/unix_chunker_lex.o$(ct)\
../SimpleGrammarLib/unix_chunker_yacc.o$(ct)\
../StructDictLib/ItemsContainer.o$(ct)\
../StructDictLib/Ross.o$(ct)\
../StructDictLib/StdRoss.o$(ct)\
../StructDictLib/TempArticle.o$(ct)\
../SynanDmnLib/JVisualSynAnParamBuilder.o$(ct)\
../SynanDmnLib/Morphan.o$(ct)\
../SynanDmnLib/SynanDmn.o$(ct)\
../SynanLib/Adverbs.o$(ct)\
../SynanLib/AnalyticalForms.o$(ct)\
../SynanLib/BaseRules.o$(ct)\
../SynanLib/foreign_term.o$(ct)\
../SynanLib/FormatCallerInit.o$(ct)\
../SynanLib/FragCoord.o$(ct)\
../SynanLib/FragDisrupt.o$(ct)\
../SynanLib/FragPustycha.o$(ct)\
../SynanLib/gen_chains.o$(ct)\
../SynanLib/Gleiche.o$(ct)\
../SynanLib/HomonymsKiller.o$(ct)\
../SynanLib/Names.o$(ct)\
../SynanLib/noun_adjunct_group.o$(ct)\
../SynanLib/NSO.o$(ct)\
../SynanLib/Numbers.o$(ct)\
../SynanLib/Participles.o$(ct)\
../SynanLib/prepositions.o$(ct)\
../SynanLib/RuleForSimilarNounGroupClauses.o$(ct)\
../SynanLib/RusBuildInitialClauses.o$(ct)\
../SynanLib/RusClause.o$(ct)\
../SynanLib/RusFormatCaller.o$(ct)\
../SynanLib/RusGroup.o$(ct)\
../SynanLib/RusOborot.o$(ct)\
../SynanLib/RusParenthesis.o$(ct)\
../SynanLib/RusPlmLine.o$(ct)\
../SynanLib/RusSentence.o$(ct)\
../SynanLib/RusSyntaxOpt.o$(ct)\
../SynanLib/RusThesaurus.o$(ct)\
../SynanLib/RusWord.o$(ct)\
../SynanLib/Selective.o$(ct)\
../SynanLib/similar_adjs.o$(ct)\
../SynanLib/similar_advs.o$(ct)\
../SynanLib/similar_common.o$(ct)\
../SynanLib/similar_infs.o$(ct)\
../SynanLib/similar_noun_groups.o$(ct)\
../SynanLib/similar_numerals.o$(ct)\
../SynanLib/StdSynan.o$(ct)\
../SynanLib/SynanDash.o$(ct)\
../SynanLib/SynSubjPred.o$(ct)\
../SynanLib/Verbs.o$(ct)\
../SynCommonLib/BuildInitialClauses.o$(ct)\
../SynCommonLib/ClauseCollection.o$(ct)\
../SynCommonLib/Clause.o$(ct)\
../SynCommonLib/CoverageKillHomonyms.o$(ct)\
../SynCommonLib/FindTermins.o$(ct)\
../SynCommonLib/FormatCaller.o$(ct)\
../SynCommonLib/GLRFormats.o$(ct)\
../SynCommonLib/Group.o$(ct)\
../SynCommonLib/MorphVariant.o$(ct)\
../SynCommonLib/oborot.o$(ct)\
../SynCommonLib/RelationsIterator.o$(ct)\
../SynCommonLib/Sentence.o$(ct)\
../SynCommonLib/SentencesCollection.o$(ct)\
../SynCommonLib/SynPlmLine.o$(ct)\
../SynCommonLib/SyntaxInit.o$(ct)\
../SynCommonLib/ThesaurusForSyntax.o$(ct)\
../SynCommonLib/Word.o$(ct)\
../tinyxml/action_store.o$(ct)\
../tinyxml/htmlutil.o$(ct)\
../tinyxml/lex_util.o$(ct)\
../tinyxml/node_set.o$(ct)\
../tinyxml/tinystr.o$(ct)\
../tinyxml/tinyxmlerror.o$(ct)\
../tinyxml/tinyxml.o$(ct)\
../tinyxml/tinyxmlparser.o$(ct)\
../tinyxml/tokenlist.o$(ct)\
../tinyxml/xml_util.o$(ct)\
../tinyxml/xpath_expression.o$(ct)\
../tinyxml/xpath_processor.o$(ct)\
../tinyxml/xpath_stack.o$(ct)\
../tinyxml/xpath_static.o$(ct)\
../tinyxml/xpath_stream.o$(ct)\
../tinyxml/xpath_syntax.o$(ct)\
../TrigramLib/NGramFile.o$(ct)\
../TrigramLib/ReadLexFile.o$(ct)\
../TrigramLib/TagSet.o$(ct)\
../TrigramLib/TrigramLemmatizer.o$(ct)\
../TrigramLib/TrigramModel.o$(ct)\
../TrigramLib/TrigramSerialize.o$(ct)\
../TrigramLib/TrigramException.o$(ct)\
../TrigramLib/ViterbiInfo.o$(ct)\
../TrigramLib/Viterbi.o$(ct)\
../TrigramRusCorporaXml/CookedSentence.o$(ct)\

pcre = \
../PCRE/pcre_tables.o$(ct)\
../PCRE/pcre_get.o$(ct)\
../PCRE/pcre_study.o$(ct)\
../PCRE/pcre_ucp_searchfuncs.o$(ct)\
../PCRE/pcre_rml.o$(ct)\
../PCRE/pcre_xclass.o$(ct)\
../PCRE/pcre_dfa_exec.o$(ct)\
../PCRE/pcre_newline.o$(ct)\
../PCRE/pcreposix.o$(ct)\
../PCRE/pcre_info.o$(ct)\
../PCRE/pcre_refcount.o$(ct)\
../PCRE/pcre_globals.o$(ct)\
../PCRE/pcre_version.o$(ct)\
../PCRE/pcre_valid_utf8.o$(ct)\
../PCRE/pcre_config.o$(ct)\
../PCRE/pcre_exec.o$(ct)\
../PCRE/pcre_chartables.o$(ct)\
../PCRE/pcre_fullinfo.o$(ct)\
../PCRE/pcre_try_flipped.o$(ct)\
../PCRE/pcre_maketables.o$(ct)\
../PCRE/pcre_compile.o$(ct)\
../PCRE/pcre_ord2utf8.o$(ct)\


objects += $(pcre)


reserve = \
../SemanDaemon/Main.o$(ct)\
\
../SemanDmnLib/translate.o$(ct)\
../SemanDmnLib/VisualGraph.o$(ct)\
\
../Seman/GenerateNewForm.o$(ct)\
../Seman/SemStructure.o$(ct)\
../Seman/ComSemWord.o$(ct)\
../Seman/ComSemRelation.o$(ct)\
../Seman/ComSemNode.o$(ct)\
../Seman/seman.o$(ct)\
\
../SemanLib/SemanticsHolder.o$(ct)\
../SemanLib/GenerateNewForm.o$(ct)\
../SemanLib/Valency.o$(ct)\
../SemanLib/SemanticGraph.o$(ct)\
../SemanLib/SemPattern.o$(ct)\
../SemanLib/SemanticLoc.o$(ct)\
../SemanLib/SemanticCommon.o$(ct)\
../SemanLib/SemanticLength.o$(ct)\
../SemanLib/SemanticRusPrimitives.o$(ct)\
../SemanLib/RossHolder.o$(ct)\
../SemanLib/SemanticColloc.o$(ct)\
../SemanLib/HierarchyHolder.o$(ct)\
../SemanLib/SemanticIdealize.o$(ct)\
../SemanLib/SemanticSynRelation.o$(ct)\
../SemanLib/DictUnitInterp.o$(ct)\
../SemanLib/SemStructureBuilder.o$(ct)\
../SemanLib/SemanticNumeral.o$(ct)\
../SemanLib/SemanticAnswer.o$(ct)\
../SemanLib/TransferSyntaxRelationToSemantics.o$(ct)\
../SemanLib/SemanticCompar.o$(ct)\
../SemanLib/SemanticWeight.o$(ct)\
../SemanLib/TranslatorHolder.o$(ct)\
../SemanLib/SemanPattern.o$(ct)\
../SemanLib/SemanticTime.o$(ct)\
../SemanLib/RussianSynthesis.o$(ct)\
../SemanLib/SemanticTree.o$(ct)\
../SemanLib/SemanticClause.o$(ct)\
../SemanLib/SemanticStrAn.o$(ct)\
../SemanLib/SemanHypotGraph.o$(ct)\
../SemanLib/SemanticMNA.o$(ct)\
../SemanLib/AllRossesHolder.o$(ct)\
../SemanLib/SemanticLexVariant.o$(ct)\
../SemanLib/SemanticLexFuncts.o$(ct)\
../SemanLib/SemanticThesaurus.o$(ct)\
\
../Transfer/EngAdverbs.o$(ct)\
../Transfer/EngAlg_1.o$(ct)\
../Transfer/EngAlg_2.o$(ct)\
../Transfer/EngAlg_3.o$(ct)\
../Transfer/EngAlg_4.o$(ct)\
../Transfer/EngAlg_5.o$(ct)\
../Transfer/EngArticle.o$(ct)\
../Transfer/EngAtomic.o$(ct)\
../Transfer/EngBinaryTranslate.o$(ct)\
../Transfer/EngEquivs.o$(ct)\
../Transfer/EngHelper.o$(ct)\
../Transfer/EngInterp.o$(ct)\
../Transfer/EngNodeCreate.o$(ct)\
../Transfer/EngNoun.o$(ct)\
../Transfer/EngPrep.o$(ct)\
../Transfer/EngPrimitives.o$(ct)\
../Transfer/EngSynthes.o$(ct)\
../Transfer/EngTerminTranslate.o$(ct)\
../Transfer/EngTimeNodeTranslate.o$(ct)\
../Transfer/EngVerbTense.o$(ct)\
../Transfer/NodeHelper.o$(ct)\
../Transfer/TranseClause.o$(ct)\
../Transfer/TranslateToEnglish.o$(ct)\
../Transfer/TransPrepNoun.o$(ct)\
../Transfer/TransRels.o$(ct)\
../Transfer/TransRules.o$(ct)\
../Transfer/TransTense.o$(ct)\
\
../RossDev/CntrItem.o$(ct)\
../RossDev/NewRefArticles.o$(ct)\
../RossDev/FieldsListEditor.o$(ct)\
../RossDev/FieldList.o$(ct)\
../RossDev/HierarchyDoc.o$(ct)\
../RossDev/MainFrm.o$(ct)\
../RossDev/PocketDoc.o$(ct)\
../RossDev/Splash.o$(ct)\
../RossDev/ReportView.o$(ct)\
../RossDev/RossDoc.o$(ct)\
../RossDev/FldScroll.o$(ct)\
../RossDev/PocketForm.o$(ct)\
../RossDev/FormulaEditor.o$(ct)\
../RossDev/RossScheme.o$(ct)\
../RossDev/ChildFrm.o$(ct)\
../RossDev/ProgressForm.o$(ct)\
../RossDev/PosChoicer.o$(ct)\
../RossDev/FieldEditor.o$(ct)\
../RossDev/Hierarchy.o$(ct)\
../RossDev/FindWrongRefs.o$(ct)\
../RossDev/ReportDoc.o$(ct)\
../RossDev/font.o$(ct)\
../RossDev/FindByStrDlg.o$(ct)\
../RossDev/SemanticStrDoc.o$(ct)\
../RossDev/ArticleDoc.o$(ct)\
../RossDev/ArticleView.o$(ct)\
../RossDev/SyntaxColorizer.o$(ct)\
../RossDev/InputBox.o$(ct)\
../RossDev/OXResizeGadget.o$(ct)\
../RossDev/BasicDomenEdit.o$(ct)\
../RossDev/SemanticStrView.o$(ct)\
../RossDev/picture.o$(ct)\
../RossDev/SchemeRossChoicer.o$(ct)\
../RossDev/SizeFormView.o$(ct)\
../RossDev/NewArticleWizard.o$(ct)\
../RossDev/ImportForm.o$(ct)\
../RossDev/SetEditor.o$(ct)\
../RossDev/RossDev.o$(ct)\
../RossDev/NewTextEntry.o$(ct)\
../RossDev/Translations.o$(ct)\
../RossDev/rowcursor.o$(ct)\
../RossDev/ValueDlg.o$(ct)\
../RossDev/WordList.o$(ct)\
../RossDev/GridCtrl.o$(ct)\
../RossDev/SignatEditor.o$(ct)\
\
../StatTxtDat/StatTxtDat.o$(ct)\


gui = \
../common/COMSyntaxHolder.o$(ct)\
../VisualSynan/VisualClause.o$(ct)\
../VisualSynan/MainFrm.o$(ct)\
../VisualSynan/VisualSynanView.o$(ct)\
../VisualSynan/Splash.o$(ct)\
../VisualSynan/SynReport.o$(ct)\
../VisualSynan/SynanWrapper.o$(ct)\
../VisualSynan/SentenceLine.o$(ct)\
../VisualSynan/ChildFrm.o$(ct)\
../VisualSynan/DlgHom.o$(ct)\
../VisualSynan/VisualSentence.o$(ct)\
../VisualSynan/VisualSentences.o$(ct)\
../VisualSynan/VisualGroup.o$(ct)\
../VisualSynan/ReportDoc.o$(ct)\
../VisualSynan/WaitThread.o$(ct)\
../VisualSynan/VisualSynanDoc.o$(ct)\
../VisualSynan/WaitDlg.o$(ct)\
../VisualSynan/VisualSynan.o$(ct)\
../VisualSynan/VisualGroups.o$(ct)\
../VisualSynan/VisualWord.o$(ct)\
../graphan/RMLLicense.o$(ct)\
../graphan/graphan.o$(ct)\
../graphan/ComGraphmatFile.o$(ct)\
../MorphCorpusCreator/SemanticMarkup.o$(ct)\
../MorphCorpusCreator/Main.o$(ct)\
../MorphCorpusCreator/MorphCorpusCreator.o$(ct)\
../Checker/ProceedDlg.o$(ct)\
../Checker/GriIni.o$(ct)\
../Checker/Checker.o$(ct)\
../Checker/GriThrPB.o$(ct)\
../Checker/CheckerDlg.o$(ct)\
../TrigamText2Xml/TrigamText2Xml.o$(ct)\
../SynAn/ComRelationIterator.o$(ct)\
../SynAn/COMWord.o$(ct)\
../SynAn/COMClauseType.o$(ct)\
../SynAn/SynAn.o$(ct)\
../SynAn/COMGroup.o$(ct)\
../SynAn/COMClauseVariant.o$(ct)\
../SynAn/Unit.o$(ct)\
../SynAn/COMSentencesCollection.o$(ct)\
../SynAn/COMHomonym.o$(ct)\
../SynAn/COMClause.o$(ct)\
../SynAn/ComRelation.o$(ct)\
../SynAn/COMSentence.o$(ct)\

#germansyn = \
../GerSynanLib/GerGroup.o$(ct)\
../GerSynanLib/Familien.o$(ct)\
../GerSynanLib/GenitNP.o$(ct)\
../GerSynanLib/GerSynan.o$(ct)\
../GerSynanLib/GerOborot.o$(ct)\
../GerSynanLib/GerClause.o$(ct)\
../GerSynanLib/Verb.o$(ct)\
../GerSynanLib/SimilarNP.o$(ct)\
../GerSynanLib/GLRFormats.o$(ct)\
../GerSynanLib/GerSubject.o$(ct)\
../GerSynanLib/Adjektiv.o$(ct)\
../GerSynanLib/prepositions.o$(ct)\
../GerSynanLib/GerFormatCaller.o$(ct)\
../GerSynanLib/GerGeo.o$(ct)\
../GerSynanLib/AdjNomen.o$(ct)\
../GerSynanLib/GerAnalytical.o$(ct)\
../GerSynanLib/Additions.o$(ct)\
../GerSynanLib/GerWord.o$(ct)\
../GerSynanLib/GerSyntaxOpt.o$(ct)\
../GerSynanLib/GerThesaurus.o$(ct)\
../GerSynanLib/GerBuildInitialClauses.o$(ct)\
../GerSynanLib/Numeralia.o$(ct)\
../GerSynanLib/GerBaseRules.o$(ct)\
../GerSynanLib/GerSentence.o$(ct)\

germansyn = \
../GerSynanLib/GerAnalytical.o$(ct) \
../GerSynanLib/GerBaseRules.o$(ct) \
../GerSynanLib/GerBuildInitialClauses.o$(ct) \
../GerSynanLib/GerClause.o$(ct) \
../GerSynanLib/GerFormatCaller.o$(ct) \
../GerSynanLib/GerGroup.o$(ct) \
../GerSynanLib/GerOborot.o$(ct) \
../GerSynanLib/GerSentence.o$(ct) \
../GerSynanLib/GerSubject.o$(ct) \
../GerSynanLib/GerSyntaxOpt.o$(ct) \
../GerSynanLib/GerThesaurus.o$(ct) \
../GerSynanLib/GerWord.o$(ct)


objects+=$(germansyn)
